apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: frontend
  name: loadgen-dep
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: loadgen
  template:
    metadata:
      labels:
        app: loadgen
    spec:
      containers:
      - name: loadgen-con
        image: python:3.8-slim
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: loadgen
spec:
  selector:
    app: loadgen
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: loadgen-dep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: loadgen-dep
  minReplicas : 1
  maxReplicas : 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
